version: '3.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    command: >
      bash -c
      "(sleep 15s &&
      kafka-topics --create --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 --topic product-views-topic &) && /etc/confluent/docker/run"

  postgres:
    image: hepsiburada/postgres:13.1-case
    ports:
      - "5432:5432"
    environment:
      - PGDATA=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=data-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  kafka-network:
    name: kafka-network
